### ISSUE TITLE
Configuration is lost when the process terminates

### ISSUE THREAD

**Issue by nostdm** [lupoDharkael/flameshot#14]
Hello, thanks for creating this neat tool.
There is one issue that I'm experiencing and I'm not sure how to fix it.
Whenever I restart the flameshot process, the configuration resets and I have to configure it again.

**Steps:**

1. Start flameshot.
2. Change configuration using `flameshot config` or edit the `~/.config/Dharkael/flameshot.conf` file.
3. Terminate the flameshot process or exit the application.
4. Start a new instance of flameshot.
5. Configuration is reset back to default values.

**Version:**

flameshot -v output:
```
Flameshot 
Compiled with QT 5.9.1
```
AUR version:
```
0.4.1
```

**System:**

- Arch Linux
- i3 window manager

**Comment by lupoDharkael** [comment]
thanks for the information, I'll check it later! (and yes, the -v flag needs a fix because depending on the packaging process it may not show the version)

**Comment by lupoDharkael** [comment]
I suspect you don't have `initiated=true` in your configuration file, that's what Flameshot checks in order to know if thats the first launch of the program and if it doesn't exists then sets all the default values.

I wanted to change it using a more smart approach but I don't want to break the compatibility and configuration before the 1.0 release.
I don't know what exactly caused the delete of the `initiated` value.
Did you always have persistent configuration until you did something specific? maybe you deleted that line accidentally.

**Comment by lupoDharkael** [comment]
Ok I've found a problem in the code. People using Flameshot before a specific version are not affected by the bug. Anyway I'm going to release a minor version with the fix. It should be in AUR in a few hours after the release.

**Comment by nostdm** [comment]
Great, I've added `initiated=true` to the config file and now everything works.

I haven't done anything special with the configuration so this has been happening since I installed it. But I think you already know this since you found the bug. 

Thanks a lot!

**Comment by lupoDharkael** [comment]
I'm closing the issue as it should be fixed now.
