### ISSUE TITLE
The Github pages of flameshot has been initially built. 

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#145]
The Github pages of flameshot:
![image](https://user-images.githubusercontent.com/10769951/36893386-d644a356-1e42-11e8-89fc-dee159cc5612.png)
The official website and the document are integrated, it's powered by [docsify](https://docsify.js.org).

If you are interested in localized translations of flameshot documents, please send your pr to this [repo](https://github.com/flameshotapp/flameshotapp.github.io).

**Comment by lupoDharkael** [comment]
I'm not very familiar with github organizations but what are the implications of arbitrary people joining the organization? aren't the PR's enough to manage contributions? If people joining the organization implies the right to modify the repos I don't think it's a good idea.

**Comment by ZetaoYang** [comment]
@lupoDharkael I have made amendments about the above words.

**Comment by ZetaoYang** [comment]
@lupoDharkael I think you can add a project URL (https://flameshotapp.github.io) to this project.

**Comment by ZetaoYang** [comment]
@lupoDharkael I have a suggestion: Add a list of translators in the software About section. Thanks for their contribution to flameshot internationalization.

**Comment by lupoDharkael** [comment]
I'll Add the information about the translation repo and the github page.

I'll be "merging" the translations back into Flameshot from time to time as most projects do.
Concerning the organization, it's useful, but people shouldn't be added just because the want to contribute. Some people could just want to do a contribution just one time and never contribute again. 
The PR is a good mechanism to filter and review modifications to the main project and it is more important as the project becomes bigger.
Most software projects only add trusted people to the organization and that's how I think it should be done.
About the recognition of the translators, I think it's a good idea.

**Comment by ZetaoYang** [comment]
@lupoDharkael Translates folder may be put into git sub-modules, but in this case CI should be modified.

**Comment by lupoDharkael** [comment]
A lot of distros maintain packages of Flameshot. I want to preserve backwards compatibility until 1.0, changing how the program has to be packaged very frequently is not a good thing.
