### ISSUE TITLE
Add Imgur Warning

### ISSUE THREAD

**Issue by Netroxen** [lupoDharkael/flameshot#180]
Please add a warning when uploading an image directly to Imgur, at-least until personal Imgur account support is added. It's very easy to accidentally upload a sensitive image and not be able to subsequently remove it.

On that note, a log file with the links of past uploads would be pretty nice...

**Comment by anarcat** [comment]
at least if the "delete" url was kept somewhere, that would be slightly safer.

**Comment by AlfredoRamos** [comment]
I think a delete button is a good idea.

Imgur provides a URL to delete anonymous images, so a button to open that URL would allow the user to delete the image.

That page would only delete the image with the user confirmation, so that would also prevent from accidental deletions.

@lupoDharkael what do you think about it? I could create a pull request.

**Comment by lupoDharkael** [comment]
@AlfredoRamos so that button would be in the widget that appears after the image has been uploaded?

**Comment by AlfredoRamos** [comment]
@lupoDharkael Yes, there will be 4 buttons. The new button only opens a link with the user's web browser (the same way as Open URL).
