### ISSUE TITLE
High cpu and memory usage.

### ISSUE THREAD

**Issue by Honghe** [lupoDharkael/flameshot#231]
**Describe the bug**
High cpu and memory usage.

```
ps aux|grep flameshot
PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
22004  1.2   0.6     649796 48748 ?        Sl   21:38   0:00 flameshot
```

**To Reproduce**
Start flameshot

**Expected behavior**
A low cpu and memory usage.

**Desktop (please complete the following information):**
 - Ubuntu 16.04.4 GNOME
 - Version commit cf7066a build with qt 5.5.1
 -  Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
 - memory 8G

**Comment by lupoDharkael** [comment]
Flameshot's CPU usage is normally 0% because the process is blocked most of the time unless you interact with it. You can see it with `top` or `htop` instead of a single evaluation of the process freshly launched. A constant non 0 CPU usage when you are not using Flameshot is an abnormal behaviour and should be reported as a bug.

That memory usage showed by `ps` is about 50MB, an most of the memory is allocated by QT's shared libraries. Flameshot's own memory is about 7MB after the start of the process and the other memory is shared across all the programs using QT.
