### ISSUE TITLE
Add option to exit after screenshot

### ISSUE THREAD

**Issue by mbirth** [lupoDharkael/flameshot#257]
I rarely take screenshots so I don't need flameshot to linger around after the screenshot has been saved/uploaded/copied to clipboard. Also starting time from `flameshot gui` is no issue at all. So an option to have it exit itself after a screenshot is done would be awesome.

**Comment by lupoDharkael** [comment]
This could be implemented but take in consideration that if you close Flameshot after copying a something into the clipboard, you wont be able to paste it. The original process needs to be running.
This is the main reason for Flameshot to keep running in the background as RAM is pretty cheap these days.

**Comment by mbirth** [comment]
Oh, that makes sense. Although I could swear `gnome-screenshot` closes after selecting "Clipboard" and I can still paste it into apps. Maybe you can add something like "auto-close xx minutes after capture" or wait for a paste event and close shortly after that. (And while RAM for current machines may be cheap, it is the opposite if you have an old PC or impossible with a Raspberry Pi.)

**Comment by lupoDharkael** [comment]
I'l try to check Gnome's screenshot tool source code and see what they do to solve the issue. Thanks for the suggestion.

**Comment by harmancasvi** [comment]
I join this request.

**Here's my point:** I doesn't matter if RAM is chap or not these days, open source is all about choices.
@lupoDharkael  your screenshot tool really is a gem, I'm using it as my primary (switched from scrot because of the editing options) but I'd really appreciate an option to auto close the app once it has done its job.

**Regarding RAM usage here's an example:** I use A LOT of Firefox tabs for work, I have Skype running, Wire, Spotify, etc. They do use **a lot** of RAM (f**k electron). Due to the nature of the apps I need those running but not your screenshot tool, that one I can call whenever needed.
A screenshot tool souldn't be running all the time (at least in my opinion) and that's why I used scrot, so I'd really like a simple switch kinda **`flameshot [arguments] -k [other-options]`** that kills flameshot process after the actual screenshot's been taken, that way people who want it running can call it without `-k` just as it is right now, and people like us can call the tool with the `-k` for one-time use, it's a win-win :-)

Just like @mbirth said, I don't care much about launch time, it's trivial compared to a screenshot tool using ~35MB of my RAM all the time without any need or choice. If all apps would behave like this I'd need 16GB of RAM just by launching the basic ones hahah

**Comment by tobias-haenel** [comment]
If you are using a clipboard manager, closing the copy source application shouldn't be an issue. Most of them implement a copy history, which persists copied contents after an application was closed. That is propably why it works in gnome (it uses gsd-clipboard).

https://en.m.wikipedia.org/wiki/Clipboard_manager

**Comment by JonathanAJ** [comment]
Yes, don't make sense the process running without use it, the clipboard manager approach could be better. Thanks for awesome app!

**Comment by grandfso** [comment]
I would like to join the request as well. Something like `flameshot gui --kill` would do the trick for me as I have mapped this command to the Printscr key in system config.
Also, in Gnome, when you copy something to clipboard from the browser, then close the browser, the copied content is still there (I assume this is what @tobias-haenel explained).

**Comment by AdsonCicilioti** [comment]
I also take my Vote for this feature.

My dirty solution is:
`flameshot gui & sleep 30; kill $(ps aux | awk '/[f]lameshot/ {print $2}')`

I created one custom shortcut over SUPER+PRINTSCRN keys. Where set 30 seconds. Sufucient time for create my draws and anotations.

**Comment by KawaiDesu** [comment]
Any updates on this? Flameshot is awesome but I don't want to keep it running all the time. I already have cinnamon with `csd-clipboard` eating 22M of memory, I'd like to not also keep flameshot (which is eating 82M, for a moment).
Thanks.

**Comment by lupoDharkael** [comment]
Implemented in https://github.com/lupoDharkael/flameshot/commit/cbb4727786a612d986f1830530f9b8028f08a205

**Comment by brianjmurrell** [comment]
> Implemented in [cbb4727](https://github.com/lupoDharkael/flameshot/commit/cbb4727786a612d986f1830530f9b8028f08a205)

Does it use the desktop clipboard manager to save the snapped image before it exits?

Any ETA on a next release that will include this functionality?

**Comment by JurisMajors** [comment]
@brianjmurrell I have made a patch that saves it to xclip clipboard manager in #559 , so you dont lose your image after adding this...

**Comment by brianjmurrell** [comment]
So does that mean that the answer to my question is _no, the snapped image is not saved to the desktop clipboard manager and lost when flameshot exits with the option in this PR enabled_?

If so, that would seem to neuter much of the usefulness of this option.

**Comment by JurisMajors** [comment]
@brianjmurrell as far as I know, that is true yes.

**Comment by cptX** [comment]
I think this request to close after one shot is very important and useful. I wanted to map it to my printscr button but I don't want it to stay around after taking the screenshot. So the lack of this feature is blocking me from making it my primary screenshot application at the moment.

**Comment by avindra** [comment]
Close after capture was removed on #1103 .

Is there a discussion somewhere on why this was done or what bugs it introduced?

FWIW I am able to reuse flameshot after manually killing the daemon.

**Comment by borgmanJeremy** [comment]
The last three releases had bugs related to close after capture and the interaction between image uploading,notifications, and the clipboard. Also it causes massive confusion that with this option enabled the clipboard cannot work. 

Basically this option added a layer of additional required testing and had unseen interactions with the other parts of Flameshot. I simply did not have the bandwidth to continually support this feature and I would rather focus on core features.

I also really don't agree with the premise that saving a few MB of RAM is worth this effort.

Also one can easily create a script to mimic this behavior and launch flameshot with that script.

**Comment by avindra** [comment]
> Also one can easily create a script to mimic this behavior and launch flameshot with that script.

Not necessarily, since e.g., `flameshot gui` doesn't block on the command line. 

 A workaround might be to add a sleep as @AdsonCicilioti described: https://github.com/flameshot-org/flameshot/issues/257#issuecomment-457682427 . But that method is potentially disastrous. For example, if you spend more than 30 seconds annotating your screenshot, you run the risk of losing all your work.

> I also really don't agree with the premise that saving a few MB of RAM is worth this effort.

Fair enough, but I and others on this thread would appreciate the RAM back :smile:

**Comment by borgmanJeremy** [comment]
There's another issue open (on mobile so don't have the reference) to add a dbus call to close the daemon. This should make it more scriptable.

**Comment by brianjmurrell** [comment]
> I also really don't agree with the premise that saving a few MB of RAM is worth this effort.

A "few MB"?

VmPeak:	 1348628 kB
VmSize:	 1284072 kB

That's 1.2GB, not a few MB.

What do you think the outcome would be if every one of dozens of applications wasted "a few MB" (1.2 thousand "few" to be exact) just sitting around waiting, just in case somebody wants to use it?

You can see what the outcome is.  Load a few dozen apps on a Windows PC, all of which want to be in the "system tray" (which seems to be just about every Windows app) so that they load "quickly" on the rare occasion that they are used.  You end up with PCs that need dozens of GBs of RAM just so all of those applications can sit around waiting to be used.

Just sayin'.

**Comment by thepurple** [comment]
It doesn't consume 1.2Gb or something like that in the idle mode (no active editor). Usually it consumes nearly 20-40Mb (depends on platform).

**Comment by borgmanJeremy** [comment]
Close after capture will not be added back in its old form. This is the final decision.

**Comment by mmahmoudian** [comment]
@brianjmurrell how did you end up with those numbers? for me it doesn't use much:

```sh
ps --pid $(pgrep flameshot) -o pid,%cpu,%mem,vsz,rss,command | numfmt --header --to=iec --field 4-5
```

![image](https://user-images.githubusercontent.com/390889/116373790-5a243000-a816-11eb-8907-7601d9ea1d2b.png)

Not the resident memory nor the total VM size does not even get close to 5MB

**Comment by thepurple** [comment]
20-40 it consumes on MacOS 
On Windows 5-6Mb
 
![flameshot_win_ram](https://user-images.githubusercontent.com/15923484/116408944-0b898c80-a83c-11eb-941f-8a0940d79739.png)

**Comment by basaran** [comment]
Hello, ram is not the only issue. Besides memory, it also uses cpu as as background process. While minimal, combine that with the tens of thousands of users at the least, keeping it off could make the planet a bit greener.
