### ISSUE TITLE
Missing French translation for GNOME Shell launcher context menu

### ISSUE THREAD

**Issue by orschiro** [lupoDharkael/flameshot#299]
Dear lupoDharkael, 

For consistency reasons, where can I find the strings to translate below two elements into French?

Thank you.

![image](https://user-images.githubusercontent.com/170947/43762126-53c409ec-9a27-11e8-9e3d-b5aa7ccd2f51.png)

**Comment by lupoDharkael** [comment]
Check this information:
https://github.com/flameshotapp/translation-instruction

**Comment by orschiro** [comment]
Thank you. It is clear to me that I need to edit [Internationalization_fr.ts](https://github.com/lupoDharkael/flameshot/blob/master/translations/Internationalization_fr.ts). However, inside that file, I cannot find the aforementioned strings.

Am I missing something?

**Comment by hosiet** [comment]
That said, in fact `desktop` files can be internationalized (i18n-ed) using some certain toolchain so that the translatable strings are extracted and translators don't need to manually edit the desktop file (they only need to deal with PO files). Some projects (like GNOME or KDE) have already integrated such facilities.

That would need some non-trival changes to the build system. We might be able to deploy it after 0.6 release.

**Comment by orschiro** [comment]
Thank you very much for your help!

I have created a pull request at https://github.com/lupoDharkael/flameshot/pull/301

:-)

**Comment by orschiro** [comment]
It's been merged.
