### ISSUE TITLE
Compilation on gentoo

### ISSUE THREAD

**Issue by TheMegaTB** [lupoDharkael/flameshot#3]
So I attempted to compile on Gentoo Linux and the compilation fails at `make`:
![2017-07-02-16 54 08](https://user-images.githubusercontent.com/5037967/27770878-ea5b12be-5f46-11e7-932b-08ad5976883f.png)
Any idea/hint what package/dependency could be missing?

**Comment by lupoDharkael** [comment]
Flameshot requires QT5 to work. Check that you are using a proper version of qmake
https://wiki.gentoo.org/wiki/Qt#Compiling_programs_that_use_qmake_and_need_Qt5

**Comment by TheMegaTB** [comment]
Thanks for the quick reply!
Indeed compilation went just fine with the qt5 qmake version.
When executing flameshot though it simply does nothing. I ran:
```
./flameshot gui -p /tmp
```
and it returned exit code 0 but didn't open any GUI nor save a screenshot.

**Comment by lupoDharkael** [comment]
Try executing `flameshot` without parameters, it will open the app without doing work and it should appear in the notification area as a tray icon. If it works then the problems is due to something related to the DBus protocol as it is used to launch and interact with the running instance of Flameshot.

**Comment by TheMegaTB** [comment]
That was the issue thanks! Maybe you should add in the README that the mode commands communicate with the already running tray instance.

One proposal:
When using the area select it would be nice to have ENTER actually save the image. Currently ENTER as well as ESC exit the selection mode without saving but to me it would seem plausible that pressing ENTER saves the current selection.

**Comment by lupoDharkael** [comment]
Pressing Enter actually copies the capture to your clipboard, if you want to save it you can simply press Ctrl+s.

About the naming convention. I'm open to talk about what the application should use or ways to configure it. If you want to do so please, open a new issue because this one is solved and it's better to have problem specific issues.
