### ISSUE TITLE
Make flameshot exit with different exit code than normally when screenshot is cancelled.

### ISSUE THREAD

**Issue by mikroskeem** [lupoDharkael/flameshot#302]
Right now using `flameshot gui --raw` and pressing esc to cancel makes flameshot put only "screenshot failed" into stdout, but still exits with exit code 0.

Making flameshot exit with code 1 makes scripting easier, as then user only has to check the exit code, not capture stdout and grep it.

**Comment by thebitstick** [comment]
Considering implementing Flameshot into my https://github.com/ShareXin/ShareXin for a no compromises screenshotting tool.
This enhancement request from @mikroskeem  would be great.
Currently my app checks for gnome-screenshot and then spectacle.
Since flameshot has Wayland support for both GNOME and Plasma, using this seems like a no brainer.

**Comment by mikroskeem** [comment]
I thought this would be a small change and it'd take less than 2 months to implement, I'm going to open up a PR implementing this feature.

**Comment by mikroskeem** [comment]
Amazing, I didn't realize that main.cpp needs a bunch of `return`s, that's where I got stuck.

**Comment by Nimmidev** [comment]
This does not work for me on Linux with `Flameshot v12.1.0 (-) / Compiled with Qt 5.15.5`.

Running `flameshot gui -r` results in a zero exit code regardless of if the screenshot was aborted or not.
