### ISSUE TITLE
Doesn't seem to be working on ArchLabs

### ISSUE THREAD

**Issue by Raj2032** [lupoDharkael/flameshot#311]
When I click on the application, it does not open up anything at all. I am running ArchLabs (based on ArchLinux).

**Comment by hosiet** [comment]
See also #179 and #307 .

* What version of flameshot are you running?
* What Desktop Environment are you running?
* Can you find `flameshot` process in system process list after clicking?
* Is there any tray area on your Desktop Environment? Do other Qt programs with trays work well?
* Will manually running `flameshot gui` open up a screenshot UI?
* If you are running under KDE Plasma, can you find the tray icon as stated in #307 ?
* Have you installed `libappindicator-gtk{2,3}` packages?

**Comment by Raj2032** [comment]
I forgot the version of flameshot, and the DE was OpenBox, unfortunately I
removed ArchLabs as I know longer use this so I can't really help you out
from here guys, sorry about that.

**Comment by michaelainsworth** [comment]
Hi. I use ArchLinux and flameshot (which I LOVE), but it's recently stopped
working in some scenarios.

    Operating System: ArchLinux
    Desktop environment: i3
    Flameshot version:
        Flameshot v0.6.0
        Compiled with Qt 5.11.1
    Process list:
        [michael@archie ~]$ ps aux | grep flameshot | grep -v grep
        michael   3828  0.5  0.2 418632 34980 pts/3    Sl+  20:58   0:00 flameshot
    Running "flameshot gui":
        No graphical windows appear, the process exits immediately with code 0, no text printed to stdout/stderr.
    Running "fameshot":
        Works as expected until I annotate with the text tool.
        
I take a lot of screenshots and annotate them (primarily with blurring and
boxing).  I previously used a different graphical editor to add text, but since
text support was added to flameshot, I've been using that. However, for the
past week or so, I am unable to take a screenshot after using the text tool.
That is, I take screenshot 1 with a box, screenshot 2 with an arrow, screenshot
3 with text, and all of them save to disk correctly. However, as soon as I try
to add another screenshot, either by left-clicking the flameshot icon, or by
right clicking the flameshot icon and clicking "Take Screenshot", nothing
happens. I'd love for this to be fixed, because the text tool is what makes
flameshot "complete" for me.

Good job, mate.

**Comment by michaelainsworth** [comment]
Just to help out, the problem only occurs when using the text tool, then SAVING the file. I.e., if instead of saving the file you "Leave the capture screen", "Upload the selection to Imgur", "Choose an app to open the capture" or "Copy the selection into the clipboard", then flameshot will continue to work. It's only if you use the text tool, then save it to a file that it stops responding. Hope that helps.

**Comment by michaelainsworth** [comment]
Legend.

What is the policy re distributing your upstream changes to the various distros? E.g., how long until ArchLinux picks it up?

**Comment by hosiet** [comment]
That completely depends on the packager of Arch Linux. @farseerfc it might be a good idea to cherry-pick this fix recently.

**Comment by farseerfc** [comment]
Sorry for the delay (don't know why this notification missed my inbox).
flameshot 0.6.0-2 is just released on Arch Linux and it contains this patch.
