### ISSUE TITLE
error while loading shared libraries: libQt5Widgets.so.5

### ISSUE THREAD

**Issue by IgorDePaula** [lupoDharkael/flameshot#336]
**Flameshot version**
0.6

**Describe the bug**
igor@pronon-06:~/Downloads$ flameshot
flameshot: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

**To Reproduce**

I installed it on ubuntu 18.04,and on call it in command line, I receive the error above.

**Expected behavior**I expected that application open

**System Information**
Ubuntu 18.04 64bits

**Comment by hosiet** [comment]
Okay, here's the question:

* Where did you retrieve the flameshot v0.6 `.deb` file? Is it built by yourself or downloaded from the releases page on GitHub project? Or was you installing from the AppImage file instead?

* How did you install the `.deb` file? Did you install with `dpkg -i` or `apt install` or some other commandline / GUI tools?

**Comment by IgorDePaula** [comment]
Yes, I installed with .deb file on dpkg command.

**Comment by hosiet** [comment]
Then it's not about flameshot and the problem is sole about how to use debian-based linux distributions like Ubuntu. Remember **NEVER** use `dpkg -i` to install `.deb` packages on contemporary debian-based Linux, e.g., those newer than Ubuntu 16.04 since dpkg never handles package dependency. Please use `apt install` to install those packages and the package name must be either a relative path or an absolute path. For example, `[sudo] apt install ./flameshot_*.deb`.

Besides, installing using `dpkg -i` (without libQt5 installed) should have raised error messages to you. Did you see those errors or have you just ignored them?

**Comment by IgorDePaula** [comment]
Haven't errors on install by dpkg. Now I'll try install by apt

**Comment by IgorDePaula** [comment]
By apt install fines, thank you very much
