### ISSUE TITLE
imgur upload

### ISSUE THREAD

**Issue by laloune** [lupoDharkael/flameshot#381]
First a huge thank you for your great work, that is the software I've been looking for a long time. The idea to edit the enhancements of the screenshot such as arrows, marking text and so on is just brillant.

Just a critic, I find the possibility to upload to imgur not compatible with a professional use, since users often shoot pictures of stuff they should not take of (users are users if you know what I mean) and they are one click away of a catastrophe...

making the button optional would be a nice improvement from my point of view

**Comment by AlfredoRamos** [comment]
This can be easily done using a scope in the `qmake` project file, however I'm not sure if that would be the best way to do it.

The users need to change the settings? because you could disable the tool, make the configuration file as read-only and copy that file to all the clients, then they won' be able to enable that tool to upload screenshots.

**Comment by laloune** [comment]
yeah this could be a solution when rolling out the tool

otherwise this could be enough to tell the users to deactivate the imgur option in the config

thanks!
