### ISSUE TITLE
Add .deb or .snap for Ubuntu

### ISSUE THREAD

**Issue by ericoporto** [lupoDharkael/flameshot#46]
If possible, please release this software for Ubuntu, it would be very useful for me as a developer.

**Comment by ManuelLR** [comment]
Actually you can try the AppImage generated in the latest build. You can download  here: https://transfer.sh/10wJZK/Configure_Flameshot-4a2aecd-x86_64.AppImage
After download it, you must give run permission with this command `chmod +x ./Configure_Flameshot-4a2aecd-x86_64.AppImage`

The build details are here: https://travis-ci.org/lupoDharkael/flameshot/jobs/324320559

To launch you can execute:

- `./Configure_Flameshot-4a2aecd-x86_64.AppImage` to launch and see as a tray icon
- `./Configure_Flameshot-4a2aecd-x86_64.AppImage gui` to start the "shot" now

I know that isn't the best solution but It's a patch while the .deb or snap is created

**Comment by julian-alarcon** [comment]
Snap is the recommended for multiple distros, not only Ubuntu.
You can get some help from here: http://snapcraft.io/

**Comment by alexanderadam** [comment]
Related but not the same: it would be wonderful if there would be an PPA to ensure current versions. Or should I (or someone) rather create a new issue for this?

**Comment by ZetaoYang** [comment]
@ericoporto I will release flameshot on PPA for Ubuntu.

**Comment by lupoDharkael** [comment]
Check this: https://twitter.com/popey/status/949087185533329408

**Comment by ZetaoYang** [comment]
:tada: .rpm and .deb package was built successfully.
https://travis-ci.org/ZetaoYang/flameshot/builds/327070284
support : 
      - OS=fedora DIST=25
      - OS=fedora DIST=26
      - OS=ubuntu DIST=xenial     //16.04 LTS
      - OS=ubuntu DIST=yakkety  //16.10
      - OS=ubuntu DIST=zesty      //17.04
      - OS=debian DIST=jessie      //8
      - OS=debian DIST=stretch    //9

P.S. Not support Ubuntu 14.04 LTS, because the Qt version of the default official source is 5.2.1, flameshot does not support. But this does not mean that you can not run flameshot on Ubuntu 14.04.

**Comment by 4goodapp** [comment]
@ZetaoYang Will the Stretch deb file work for Buster (Debian testing)?

**Comment by 4goodapp** [comment]
@ZetaoYang Can you link the deb file please.

**Comment by ZetaoYang** [comment]
@4goodapp I have not done the test for debian buster. All the compilation and packaging, are done in the docker environment. 

Yes, I will release. But I need to improve this process, then I will provide a link to the deb and rpm file for testing.

**Comment by nemonein** [comment]
To developers, I thank you for your great effort.

I have built Deb packages for Ubuntu Xenial and Artful. It was quite an easy job, because 'debian' code was already included in the source.
Anyone who would like to use Flameshot but have difficulties in compiling, can use my PPA at their own risk. Or just download Deb file there.

`ppa:nemonein/tailored (https://launchpad.net/~nemonein/+archive/ubuntu/tailored)`

**Comment by ZetaoYang** [comment]
@nemonein nice!

**Comment by reiabreu** [comment]
@nemonein Will give it a try, thank you,

**Comment by ZetaoYang** [comment]
@nemonein  @4goodapp Release .rpm, . deb, .AppImage and Windows portable port for testing!
see #86 .

**Comment by hosiet** [comment]
To whom it might concern, I intend to maintain flameshot *officially* inside Debian. Take a look at https://salsa.debian.org/Debian/flameshot .

Pushing it down in Debian will cause it migrate to all other deb-based linux distributions later. My wish is to get it into Ubuntu 18.04 LTS, but no guarantee will be made yet.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/releases/tag/v0.5.1
