### ISSUE TITLE
[Feature] Support scroll screenshot

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#55]
The scrolling screenshot interaction of this Mac application Xnip is worth learning, I think flameshot can also be achieved.

the gif(compressed) animation:

![scroll screenshot-compressed](https://user-images.githubusercontent.com/10769951/34612478-f5c56940-f264-11e7-9a62-91a076e65cfb.gif)

**Comment by lupoDharkael** [comment]
I don't think this will be implemented as Flameshot works with static images.
This approach makes portability way easier for multiple desktops (compositors) and operating systems.

 I would be nice to have something like this but it doesn't fit in the actual design of the project.

**Comment by Korb** [comment]
> lupoDharkael closed this as completed on Jan 6, 2018

More precisely, "not planned"?

**Comment by mmahmoudian** [comment]
Thanks @Korb for pointing out the duplicate. I will close this one in favor of the other because there is more discussion on the other thread.

**Comment by dhay734** [comment]
I for one would love to have that. Planning to migrate from Windows 10 to Linux, found Flameshot a bit by accident, and it has the ease of use I was looking for to replace Snagit (from Techsmith) which I was using before. I can do without having to capture video (would be nice but not a must for me), but I am missing sorely the "scrolling capture" found in Snagit. That is the only reason it is still installed. I would rather go full open source and support the projects I like rather than closed source publishers, but that scroll capture is a must for me (often guiding people through troubleshooting steps and need all options or all variants shown, not just what's on the main screen at one point).
