### ISSUE TITLE
Defining naming schemes for output files

### ISSUE THREAD

**Issue by TheMegaTB** [lupoDharkael/flameshot#6]
Since the application currently defaults to `screenshot.png` it would be nice to add a configuration file or cmdline switch in order to provide a naming scheme for the files e.g. based on date and time variables.

Alternatively or additionally an option to define the output file in addition to the directory would also be handy.

For the output file it would also be nice if we could use `-` instead of an actual file to utilize the bash pipes to pass the image directly on to another process (e.g. imagemagick) without storing it first:
```
./flameshot gui | magick png:- +negate screenshot.png
```
(negates the image colors *in theory* syntax might be off a bit)

**Comment by lupoDharkael** [comment]
The possibility of using pipes is definitely a "must have".
About the naming schemes; I think it should be configurable in a graphical way. I'm sure there is an important amount of not-very-terminal-friendly users who would be thankful about that.
Anyway, this is a great proposal and I want to implement these ideas in Flameshot.

**Comment by xPrzybyLx** [comment]
For defining filename scheme we can use Config file in the user directory:

`~/.config/Dharkael/flameshot.conf`

**Comment by lupoDharkael** [comment]
Here some concepts:

### **Naming Scheme**:
- The naming scheme will be defined in flameshot.conf as @xPrzybyLx has pointed out. That will make it a persistent configuration. 

- Configuration through GUI (but you can easily change the string in the config file).

- Support for conversion characters as defined in [strftime](https://www.computerhope.com/unix/strftime.htm)

- Maybe auto-numeration before the file extension when there is a file with the same name in the defined directory.

### **"Pipable" content for Flameshot commands**:

This requires to define how it will work very carefully because I have to change the DBus API in order to support this.
Flameshot is running in the background as a single instance program while you see the tray icon. Xorg is very event driven so if you want to keep the recently added content to the clipboard after a capture, the event loop of the QT app must be running.
That means that when you launch a new command you are launching a new program from the same binary (it has 2 modes, a command execution mode and the functional app itself) and it need a protocol to communicate between different process thought DBus protocol.

I could define a new parameter, something like stdout (not defined yet) and could be used like this: `flameshot gui stdout`. That would print the raw data of the capture so it could be manipulated by tools like ImageMagick.

That would need to consider 3 cases:
- No capture.
- Saved as a file: would take the data from the file.
- Saved in the clipboard only: would take the data from the clipboard.

**Comment by lupoDharkael** [comment]
I've implemented both, naming schemes and a way to print the raw images after a capture passing the flag "-r" or "--raw". It will be available in the next release!
