### ISSUE TITLE
Need text draw support.

### ISSUE THREAD

**Issue by CreateChance** [lupoDharkael/flameshot#660]
This is a very cool app on linux! I love it, thanks.
Can I draw text on captured image? I mean, I want to add some text on the image.
With this feature, this app will be perfect! :)

**Comment by cedewey** [comment]
I agree, this is the only feature missing before this becomes my screenshot tool of choice.

**Comment by impxd** [comment]
The latest version has Text support, it was one of its features, check that you have the latest version.

https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0

**Comment by lee-pai-long** [comment]
Hi @impxd I'm on ubuntu 18.04 and since the official repository only contains version v0.5.1 I tried v0.6.0 through [this ppa](https://launchpad.net/~sicklylife/+archive/ubuntu/flameshot) but I don't see any new text button whne launching it:
![Screenshot_20191128_143217](https://user-images.githubusercontent.com/7702365/69810391-12961080-11ec-11ea-9934-7c82afb616bb.png)

**Comment by impxd** [comment]
Hi there @lee-pai-long 
I'm on _Ubuntu_ 18.04 with the _.deb_ version. Maybe you need to activate that feature.

![Screenshot from 2019-11-28 11-15-33](https://user-images.githubusercontent.com/167621/69824449-66dfc700-11d1-11ea-9d87-4cbca2e613d7.png)

Hope it works for you.

**Comment by CreateChance** [comment]
@impxd Nice, that's it. But linux mint repo not update yet. Thank you~

**Comment by lee-pai-long** [comment]
Hi @impxd thanks a lot I didn't know those were configurable, sorry for the inconvenience.
