### ISSUE TITLE
More Approved Maintainers

### ISSUE THREAD

**Issue by borgmanJeremy** [lupoDharkael/flameshot#771]
@lupoDharkael Have you considered allowing more people to merge pull requests? It seems like this project has started to get a bit stale but has a bunch of interest and active people doing PR's. I would hate to see a tool that people love so much get stale or fragmented across forks.

Thanks for the great work so far!

**Comment by mmahmoudian** [comment]
I second this. It would be a shame if such an amazing FOSS project gets abandoned. This is among the tools always have on all my computers (typically installed right after my terminal app).

**Comment by Rmano** [comment]
Although I really like flameshot, I lately switched to [ksnip](https://github.com/ksnip/ksnip) due to this problem. Flameshot is still better at some things, so I still use it (for example, ksnip is somewhat broken for delayed full screen captures --- sometimes it blocks the pop-ups; on the other hand, editing is much stronger), and in my opinion, it has a nicer look. So yes, I second the petition here. Better than forking.

**Comment by szszoke** [comment]
It looks promising but one big thing that is missing - which I really like in Flameshot - is the inline editor. It's a much more seamless experience than a window popping up in my opinion. I very often use Flameshot during meetings just to highlight some parts of my screen while I'm explaining something, Unfortunately I couldn't have the same experience with ksnip.

Anyway. I am still hopeful that this project will be revived because as it is today, I don't have a good alternative that works both on my Linux and Windows machine.

**Comment by FichteFoll** [comment]
Superseded by #789.
